{{ range $i := until (int .Values.size) }}
{{- $_ := set $ "i" $i }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $.Values.labelSelector.valuePrefix }}-{{ $i }}
spec:
  podSelector:
    matchLabels:
      {{ $.Values.labelSelector.key }}: {{ $.Values.labelSelector.valuePrefix }}-{{ $i }}
  ingress:
    - from:
      - podSelector:
          matchExpressions:
          - key: {{ $.Values.labelSelector.key }}
            operator: In
            values:
            {{- include "network-policy.allowed-connections" $ | indent 12 }}
  egress:
    - from:
      - podSelector:
          matchExpressions:
          - key: {{ $.Values.labelSelector.key }}
            operator: In
            values:
            {{- include "network-policy.allowed-connections" $ | indent 12 }}
---
{{ end }}
